version: '3'
services:
  frontend:
    image: hari6091/frontend_etapa1:latest
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    image: hari6091/backend_etapa1:latest
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: database
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: rfid
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  pg-data:
