export * from './Home';
export * from './Logs';
export * from './Signin';
export * from './Signup';
export * from './Trancas';
export * from './NewLock';
export * from './SingleTranca';
export * from './SingleUser';
export * from './Usuarios';
